name: Ping Streamlit app

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app (homepage)
        run: |
          curl -fsS "https://consultation-statafricniang-hipi9oy2r5cxmqjpefudjn.streamlit.app/" > /dev/null

      - name: Ping app (health-style lightweight)
        run: |
          curl -fsS "https://consultation-statafricniang-hipi9oy2r5cxmqjpefudjn.streamlit.app/?ping=1" > /dev/null
